name: AWS SSM Parameter Store Action
description: Put parameters' value out to file by path

inputs:
  path:
    description: Path to parameters to get by
    required: true
  recursive:
    description: Whether to get recursively
    required: false
    default: 'false'
  pattern:
    description: Pattern to match parameter's base name (without path)
    required: false
  with-decryption:
    description: Whether to decrypt
    required: false
    default: 'true'
  format:
    description: Format to save as _dotenv_ or _as-is_. `outputs` are available even if it is empty
    required: false
  filename:
    description: File name to be written
    required: false

runs:
  using: node12
  main: dist/index.js

branding:
  icon: chevron-up
  color: green
